### ISSUE TITLE
Does this contains r18 tags?

### ISSUE THREAD

**Issue by linonetwo** [KichangKim/DeepDanbooru#10]
Can it detect r18 features in the pic?

**Comment by rachmadaniHaryono** [comment]
v1-20191108-sgd-e30 do contain some nsfw tag e.g nude, etc

but i don't recommend to use it if you are trying to differentiate nsfw/sfw image

**Comment by linonetwo** [comment]
I was thinking this can be used to tag ehentai images, to provide fine grain search.

**Comment by rachmadaniHaryono** [comment]
i'm using it with hydrus and already tag more than 1k images include some comic page

for full estimation i use 0.1 threshold and it give more tag than you need (and also increase false positive).

the result is vary between image. but it is great enough to especially for character namespace if you just need estimation

**Comment by linonetwo** [comment]
Thank you for your explaination!
