### ISSUE TITLE
Help with training with optional tags

### ISSUE THREAD

**Issue by Ngakk** [KichangKim/DeepDanbooru#100]
Since danbooru has added a new rating tag called sensitive, and latest pre-trained model doesn't include it I wanted to train my own model. I'm not sure on how to include the rating tags into it with step 4 instructions alone, particularly not sure how the filtered sqlite file's contents should look like. Can someone explain?

**Comment by KichangKim** [comment]
You can use `download_tags` and `make_training_database` commands. It automatically convert rating column to rating tags then DeepDanbooru can evaluate ratings as same as other tags.
