### ISSUE TITLE
Clarification of README.md

### ISSUE THREAD

**Issue by ppbrown** [KichangKim/DeepDanbooru#103]
Could you please add a bit more details in the readme, with specific directory examples?

It talks about "prepare dataset", but does not make it clear where it should live in relation to the "project"?

If I'm understanding things, maybe it would be clearer if you moved step 1, "prepare dataset", to step  6.

Then step 7 becomes

"deepdanbooru evaluate [your-dataset-directory] ...."

**Comment by KichangKim** [comment]
Hi. Dataset (including sqlite database file) can be located anywhere, you can specify its path in `project.json`.

Also, if you use pre-trained project (can download it from Releases section) and for just evaluate images, you do not need to prepare your own dataset. It only be needed for training.

**Comment by ppbrown** [comment]
Maybe I'm misunderstanding use here. Its probably best if I just say want I want to use this for.
I have a set of 1,000 images. I'm hoping to use this program to autogenerate .txt tag files for each file.
So, definitely using my own data set :)

It might be best to have a streamlined guide that handled this case specifically?

**Comment by KichangKim** [comment]
Ah, it is simple. 
`deepdanbooru evaluate [your_images_folder] --project-path [project_folder] --allow-folder --save-txt`
For details, see #90

**Comment by ppbrown** [comment]
Hmmm.
for the "download-tags" part..  I made a free api key, but when I try to use it with your script...

Seems like it pulls an empty file.

json.decoder.JSONDecodeError: Expecting value: 1line 1 column 1 (char 0)

**Comment by KichangKim** [comment]
If you only want to evaluate, you can skip 1~6. It only need for training. Pre-trained project already has `tags.txt`.

**Comment by KichangKim** [comment]
`download-tags` issue is fixed.
