### ISSUE TITLE
sqlite3.OperationalError: no such table: posts

### ISSUE THREAD

**Issue by Asmedeus998** [KichangKim/DeepDanbooru#104]
I having trouble creating sqlite database using following command

`deepdanbooru make-training-database [your_dataset_sqlite_path] [your_filtered_sqlite_path]`

**Comment by KichangKim** [comment]
Check your sqlite database structure. 
It must contains `posts` table which has columns like this:
```
posts
├── id (INTEGER)
├── md5 (TEXT)
├── file_ext (TEXT)
├── tag_string (TEXT)
└── tag_count_general (INTEGER)
```
Also, you have to prepare your database yourself (or using DanbooruDownloader)
