### ISSUE TITLE
ValueError: The `save_format` argument is deprecated in Keras 3. Please remove this argument and pass a file path with either `.keras` or `.h5` extension.Received: save_format=h5

### ISSUE THREAD

**Issue by Asmedeus998** [KichangKim/DeepDanbooru#105]
I get following error when I run this command:
`deepdanbooru train-project [your_project_folder]`

**Comment by KichangKim** [comment]
What version of your tensorflow? DeepDanbooru does not tested on the latest tensorflow. Try it with old (2.7.0) tensorflow.
