### ISSUE TITLE
The `save_format` argument is deprecated in Keras 3

### ISSUE THREAD

**Issue by aryanshukla06** [KichangKim/DeepDanbooru#106]
I have been getting the below error when I run the train-project command

> ValueError: The `save_format` argument is deprecated in Keras 3. Please remove this argument and pass a file path with either `.keras` or `.h5` extension.Received: save_format=h5

![image](https://github.com/KichangKim/DeepDanbooru/assets/160190125/66f1f6bb-849a-4596-b414-4d0d9eaffe0f)

**Comment by KichangKim** [comment]
This is known issue #105 . Some dependencies (like tensorflow-io package) are not supported on latest Python. I'll fix this when all of dependencies are released for latest Python. Until then, use old-version.

**Comment by KichangKim** [comment]
Fixed by 98d9315ab702e177de706825f9cee981c9afb928.
