### ISSUE TITLE
ResNet

### ISSUE THREAD

**Issue by BZbyr** [KichangKim/DeepDanbooru#14]

**Comment by BZbyr** [comment]
Using ResNet?

**Comment by KichangKim** [comment]
Yes. It is based on Microsoft's resnet implementation.
https://github.com/microsoft/CNTK/tree/master/Examples/Image/Classification/ResNet

**Comment by DonaldTsang** [comment]
There are so many models to choose from
- https://github.com/BertMoons/Comparing-CNN-Architectures
- https://github.com/CeLuigi/models-comparison.pytorch
- https://github.com/yeephycho/nasnet-tensorflow

@BZbyr perhaps you can pick some examples that you would like to see.

**Comment by DonaldTsang** [comment]
@KichangKim if I am allowed to say this, are there any benchmarks or tests on multiple CNN architectures?

**Comment by KichangKim** [comment]
> @KichangKim if I am allowed to say this, are there any benchmarks or tests on multiple CNN architectures?

In very early version of DeepDanbooru, I tested some types of CNN, like Inception,  Squeeze-and-Excitation and so on. But not fully benchmarked it and chose ResNet for its simplicity and good reference code (in CNTK's repository). If you want, you can test yourself by extending deepdanbooru.model namespace.
