### ISSUE TITLE
run deepdanbooru evaluate on colab

### ISSUE THREAD

**Issue by kld123509945** [KichangKim/DeepDanbooru#15]
Hi, I'm trying to test the deepdanbooru on colab. I have upload the deepdanbooru-v1-20191108-sgd-e30.zip and DeepDanbooru-master on 'drive/Colab Notebooks/' as folders, and upload an image in the test folder. The code is as follows:
> !apt-get install -y -qq software-properties-common python-software-properties module-init-tools
> !add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
> !apt-get update -qq 2>&1 > /dev/null
> !apt-get -y install -qq google-drive-ocamlfuse fuse
> from google.colab import auth
> auth.authenticate_user()
> from oauth2client.client import GoogleCredentials
> creds = GoogleCredentials.get_application_default()
> import getpass
> !google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
> vcode = getpass.getpass()
> !echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}
> 
> !mkdir -p drive
> !google-drive-ocamlfuse drive
> 
> import os
> import sys
> os.chdir('drive/Colab Notebooks')
> 
> !pip install tensorflow>=2.1.0
> !pip install Click>=7.0
> !pip install numpy>=1.16.2
> !pip install scikit-image>=2.22.0
> !pip install requests>=0.15.0
> !pip install six>=1.13.0
> 
> path = "/content/drive/Colab Notebooks/DeepDanbooru master"
> os.chdir(path)
> 
> !python setup.py install
> 
> path = "/content/drive/Colab Notebooks"
> os.chdir(path)
> !deepdanbooru evaluate deepdanbooru-v1-20191108-sgd-e30 test

However, it stops on the last command and informs as:

> Traceback (most recent call last):
>   File "/usr/local/bin/deepdanbooru", line 11, in <module>
>     load_entry_point('deepdanbooru==1.0.0', 'console_scripts', 'deepdanbooru')()
>   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
>     return ep.load()
>   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2443, in load
>     return self.resolve()
>   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/usr/local/lib/python3.6/dist-packages/deepdanbooru-1.0.0-py3.6.egg/deepdanbooru/__init__.py", line 1, in <module>
>   File "/usr/local/lib/python3.6/dist-packages/deepdanbooru-1.0.0-py3.6.egg/deepdanbooru/commands/__init__.py", line 4, in <module>
>   File "/usr/local/lib/python3.6/dist-packages/deepdanbooru-1.0.0-py3.6.egg/deepdanbooru/commands/train_project.py", line 6, in <module>
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 101, in <module>
>     from tensorflow_core import *
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/__init__.py", line 40, in <module>
>     from tensorflow.python.tools import module_util as _module_util
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 50, in __getattr__
>     module = self._load()
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 44, in _load
>     module = _importlib.import_module(self.__name__)
>   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/__init__.py", line 49, in <module>
>     from tensorflow.python import pywrap_tensorflow
> ImportError: cannot import name 'pywrap_tensorflow'

Could you help me with this problem? Many thanks!

**Comment by KichangKim** [comment]
Hi. the evaluate command is changed in latest revision, so your last command should be changed to:
```
!deepdanbooru evaluate test --project-path deepdanbooru-v1-20191108-sgd-e30
```

Also, try this:
https://stackoverflow.com/questions/54172462/tensorflow-wont-import-in-colab

**Comment by kld123509945** [comment]
Thanks so much for your kindly help! @KichangKim 
I rewrote the last command as:

> !deepdanbooru evaluate test --project-path deepdanbooru-v1-20191108-sgd-e30 --allow-folder

Now this time it stops and says:

> Traceback (most recent call last):
>   File "/usr/local/bin/deepdanbooru", line 11, in <module>
>     load_entry_point('deepdanbooru==1.0.0', 'console_scripts', 'deepdanbooru')()
>   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
>     return ep.load()
>   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2443, in load
>     return self.resolve()
>   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
>   File "/usr/local/lib/python3.6/dist-packages/deepdanbooru-1.0.0-py3.6.egg/deepdanbooru/__init__.py", line 1, in <module>
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
>   File "/usr/local/lib/python3.6/dist-packages/deepdanbooru-1.0.0-py3.6.egg/deepdanbooru/commands/__init__.py", line 4, in <module>
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
>   File "/usr/local/lib/python3.6/dist-packages/deepdanbooru-1.0.0-py3.6.egg/deepdanbooru/commands/train_project.py", line 6, in <module>
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 99, in <module>
>     from tensorflow_core import *
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/__init__.py", line 36, in <module>
>     from tensorflow._api.v1 import compat
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/_api/v1/compat/__init__.py", line 23, in <module>
>     from tensorflow._api.v1.compat import v1
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/_api/v1/compat/v1/__init__.py", line 672, in <module>
>     from tensorflow_estimator.python.estimator.api._v1 import estimator
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/__init__.py", line 10, in <module>
>     from tensorflow_estimator._api.v1 import estimator
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/_api/v1/estimator/__init__.py", line 12, in <module>
>     from tensorflow_estimator._api.v1.estimator import inputs
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/_api/v1/estimator/inputs/__init__.py", line 10, in <module>
>     from tensorflow_estimator.python.estimator.inputs.numpy_io import numpy_input_fn
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/inputs/numpy_io.py", line 26, in <module>
>     from tensorflow_estimator.python.estimator.inputs.queues import feeding_functions
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/inputs/queues/feeding_functions.py", line 40, in <module>
>     import pandas as pd
>   File "/usr/local/lib/python3.6/dist-packages/pandas/__init__.py", line 55, in <module>
>     from pandas.core.api import (
>   File "/usr/local/lib/python3.6/dist-packages/pandas/core/api.py", line 24, in <module>
>     from pandas.core.groupby import Grouper, NamedAgg
>   File "/usr/local/lib/python3.6/dist-packages/pandas/core/groupby/__init__.py", line 1, in <module>
>     from pandas.core.groupby.generic import (  # noqa: F401
>   File "/usr/local/lib/python3.6/dist-packages/pandas/core/groupby/generic.py", line 44, in <module>
>     from pandas.core.frame import DataFrame
>   File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 115, in <module>
>     from pandas.core.series import Series
>   File "/usr/local/lib/python3.6/dist-packages/pandas/core/series.py", line 84, in <module>
>     import pandas.plotting
>   File "/usr/local/lib/python3.6/dist-packages/pandas/plotting/__init__.py", line 59, in <module>
>     from pandas.plotting._core import (
>   File "/usr/local/lib/python3.6/dist-packages/pandas/plotting/_core.py", line 17, in <module>
>     import pandas.plotting._matplotlib  # noqa
>   File "/usr/local/lib/python3.6/dist-packages/pandas/plotting/_matplotlib/__init__.py", line 3, in <module>
>     from pandas.plotting._matplotlib.boxplot import (
>   File "/usr/local/lib/python3.6/dist-packages/pandas/plotting/_matplotlib/boxplot.py", line 14, in <module>
>     from pandas.plotting._matplotlib.core import LinePlot, MPLPlot
>   File "/usr/local/lib/python3.6/dist-packages/pandas/plotting/_matplotlib/core.py", line 34, in <module>
>     from pandas.plotting._matplotlib.tools import (
>   File "/usr/local/lib/python3.6/dist-packages/pandas/plotting/_matplotlib/tools.py", line 5, in <module>
>     import matplotlib.table
>   File "/usr/local/lib/python3.6/dist-packages/matplotlib/table.py", line 25, in <module>
>     from .text import Text
>   File "/usr/local/lib/python3.6/dist-packages/matplotlib/text.py", line 14, in <module>
>     from .font_manager import FontProperties
>   File "/usr/local/lib/python3.6/dist-packages/matplotlib/font_manager.py", line 103, in <module>
>     os.path.join(str(Path.home()), r'AppData\Local\Microsoft\Windows\Fonts'),
> AttributeError: type object 'Path' has no attribute 'home'

So would you help me out? Thanks again for your help!

**Comment by rachmadaniHaryono** [comment]
hi @kld123509945, i'm interested on your error

based on error message & quick google search there is similar error here

https://stackoverflow.com/questions/54934556/pathlib-library-error-in-pathlib-path-home-type-object-path-has-no-attribu

similar issue but directly on matplotlib https://github.com/Sujit-O/pykg2vec/issues/21, where op fixed it by use python3.7 instead of python3.5

**Comment by kld123509945** [comment]
Hi @rachmadaniHaryono, thanks for your help

It seems that colab is using python3.6 but not python3.7, see:
https://stackoverflow.com/questions/57026465/python-version-doesnt-change-in-colab-when-after-installing-a-different-version

Does this mean that the bug could not be fixed in the next few days? My PC is not very good at training the model as it doesn't have an Nvidia GPU, so I decide to use colab to test the deepdanbooru.

**Comment by rachmadaniHaryono** [comment]
that stackoverflow gave another alternative

maybe first try simple Path.Home, based on op edit

```
from pathlib import Path
Path.home() 
```

---

other than those on SO page, other alternative i can think of is try to organize tensorflow import so it will not import everything and hope that matplotlib will not try to use Path.Home

**Comment by kld123509945** [comment]
For a short and quick reply, does this mean that I should add these two commands before the last command? like:

> !pip install tensorflow>=2.1.0
> !pip install Click>=7.0
> !pip install numpy>=1.16.2
> !pip install scikit-image>=2.22.0
> !pip install requests>=0.15.0
> !pip install six>=1.13.0
> 
> !from pathlib import Path
> !Path.home() 
> 
> path = "/content/drive/Colab Notebooks/DeepDanbooru master"
> os.chdir(path)
> !python setup.py install
> 
> path = "/content/drive/Colab Notebooks"
> os.chdir(path)
> !deepdanbooru evaluate test --project-path deepdanbooru-v1-20191108-sgd-e30 --allow-folder

**Comment by rachmadaniHaryono** [comment]
i recommend

```python
...
path = "/content/drive/Colab Notebooks"
os.chdir(path)
# put it here
from pathlib import Path
print(Path.home())
!deepdanbooru evaluate test --project-path deepdanbooru-v1-20191108-sgd-e30 --allow-folder
```

i add print just in case that collab will skip the output of `Path.home`

**Comment by kld123509945** [comment]
Thanks so so much for your kindly help! @rrachmadaniHaryono
I'll try it now and report the result

**Comment by rachmadaniHaryono** [comment]
```
...
!from pathlib import Path
!print(Path.home())
...
```
write without exclamation mark
```
...
from pathlib import Path
print(Path.home())
...
```
if it is the error, it will raise error on this line `AttributeError: type object 'Path' has no attribute 'home'`

**Comment by kld123509945** [comment]
Thanks for your patience and help! I rewrote the code and the updated report is listed above, hmmm

**Comment by rachmadaniHaryono** [comment]
ok, so the original `Path.home` run fine

next is checking the matplotlib version, pathlib version and sys.path

```python
...
from pathlib import Path
print(Path.home())
!pip show pathlib
!pip show matplotlib
import sys
sys.path
!deepdanbooru evaluate test --project-path deepdanbooru-v1-20191108-sgd-e30 --allow-folder
```

**Comment by kld123509945** [comment]
> ok, so the original `Path.home` run fine
> 
> next is checking the matplotlib version, pathlib version and sys.path
> 
> ```python
> ...
> from pathlib import Path
> print(Path.home())
> !pip show pathlib
> !pip show matplotlib
> import sys
> sys.path
> !deepdanbooru evaluate test --project-path deepdanbooru-v1-20191108-sgd-e30 --allow-folder
> ```

I have rewrote these codes like this, and the report is:

> /root
> Name: pathlib
> Version: 1.0.1
> Summary: Object-oriented filesystem paths
> Home-page: https://pathlib.readthedocs.org/
> Author: Antoine Pitrou
> Author-email: solipsis@pitrou.net
> License: MIT License
> Location: /usr/local/lib/python3.6/dist-packages
> Requires: 
> Required-by: 
> Name: matplotlib
> Version: 3.1.2
> Summary: Python plotting package
> Home-page: https://matplotlib.org
> Author: John D. Hunter, Michael Droettboom
> Author-email: matplotlib-users@python.org
> License: PSF
> Location: /usr/local/lib/python3.6/dist-packages
> Requires: numpy, cycler, kiwisolver, python-dateutil, pyparsing
> Required-by: yellowbrick, stable-baselines, seaborn, scikit-image, plotnine, pandas-profiling, mlxtend, mizani, missingno, matplotlib-venn, magenta, keras-vis, imgaug, fbprophet, fastai, descartes, daft
> Traceback (most recent call last):
>   File "/usr/local/bin/deepdanbooru", line 11, in <module>
>     load_entry_point('deepdanbooru==1.0.0', 'console_scripts', 'deepdanbooru')()
>   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
>     return ep.load()
>   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2443, in load
>     return self.resolve()
>   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
>   File "/usr/local/lib/python3.6/dist-packages/deepdanbooru-1.0.0-py3.6.egg/deepdanbooru/__init__.py", line 1, in <module>
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
>   File "/usr/local/lib/python3.6/dist-packages/deepdanbooru-1.0.0-py3.6.egg/deepdanbooru/commands/__init__.py", line 4, in <module>
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
>   File "/usr/local/lib/python3.6/dist-packages/deepdanbooru-1.0.0-py3.6.egg/deepdanbooru/commands/train_project.py", line 6, in <module>
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 99, in <module>
>     from tensorflow_core import *
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/__init__.py", line 36, in <module>
>     from tensorflow._api.v1 import compat
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/_api/v1/compat/__init__.py", line 23, in <module>
>     from tensorflow._api.v1.compat import v1
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/_api/v1/compat/v1/__init__.py", line 672, in <module>
>     from tensorflow_estimator.python.estimator.api._v1 import estimator
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/__init__.py", line 10, in <module>
>     from tensorflow_estimator._api.v1 import estimator
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/_api/v1/estimator/__init__.py", line 12, in <module>
>     from tensorflow_estimator._api.v1.estimator import inputs
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/_api/v1/estimator/inputs/__init__.py", line 10, in <module>
>     from tensorflow_estimator.python.estimator.inputs.numpy_io import numpy_input_fn
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/inputs/numpy_io.py", line 26, in <module>
>     from tensorflow_estimator.python.estimator.inputs.queues import feeding_functions
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/inputs/queues/feeding_functions.py", line 40, in <module>
>     import pandas as pd
>   File "/usr/local/lib/python3.6/dist-packages/pandas/__init__.py", line 55, in <module>
>     from pandas.core.api import (
>   File "/usr/local/lib/python3.6/dist-packages/pandas/core/api.py", line 24, in <module>
>     from pandas.core.groupby import Grouper, NamedAgg
>   File "/usr/local/lib/python3.6/dist-packages/pandas/core/groupby/__init__.py", line 1, in <module>
>     from pandas.core.groupby.generic import (  # noqa: F401
>   File "/usr/local/lib/python3.6/dist-packages/pandas/core/groupby/generic.py", line 44, in <module>
>     from pandas.core.frame import DataFrame
>   File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 115, in <module>
>     from pandas.core.series import Series
>   File "/usr/local/lib/python3.6/dist-packages/pandas/core/series.py", line 84, in <module>
>     import pandas.plotting
>   File "/usr/local/lib/python3.6/dist-packages/pandas/plotting/__init__.py", line 59, in <module>
>     from pandas.plotting._core import (
>   File "/usr/local/lib/python3.6/dist-packages/pandas/plotting/_core.py", line 17, in <module>
>     import pandas.plotting._matplotlib  # noqa
>   File "/usr/local/lib/python3.6/dist-packages/pandas/plotting/_matplotlib/__init__.py", line 3, in <module>
>     from pandas.plotting._matplotlib.boxplot import (
>   File "/usr/local/lib/python3.6/dist-packages/pandas/plotting/_matplotlib/boxplot.py", line 14, in <module>
>     from pandas.plotting._matplotlib.core import LinePlot, MPLPlot
>   File "/usr/local/lib/python3.6/dist-packages/pandas/plotting/_matplotlib/core.py", line 34, in <module>
>     from pandas.plotting._matplotlib.tools import (
>   File "/usr/local/lib/python3.6/dist-packages/pandas/plotting/_matplotlib/tools.py", line 5, in <module>
>     import matplotlib.table
>   File "/usr/local/lib/python3.6/dist-packages/matplotlib/table.py", line 25, in <module>
>     from .text import Text
>   File "/usr/local/lib/python3.6/dist-packages/matplotlib/text.py", line 14, in <module>
>     from .font_manager import FontProperties
>   File "/usr/local/lib/python3.6/dist-packages/matplotlib/font_manager.py", line 103, in <module>
>     os.path.join(str(Path.home()), r'AppData\Local\Microsoft\Windows\Fonts'),
> AttributeError: type object 'Path' has no attribute 'home'

**Comment by kld123509945** [comment]
Btw, to check the availability of the above code, I share the whole test folder including the forked and uploaded deepdanbooru by:
https://drive.google.com/open?id=11LeejhOG36fx_nGh6v75Je2n9pVUGADd

**Comment by KichangKim** [comment]
Try below command instead of `!deepdanbooru`
```
!python -m deepdanbooru
```

**Comment by kld123509945** [comment]
Thanks! I'm running these codes now:

> path = "/content/drive/Colab Notebooks"
> from pathlib import Path
> print(Path.home())
> !pip show pathlib
> !pip show matplotlib
> import sys
> sys.path
> !python -m deepdanbooru evaluate test --project-path deepdanbooru-v1-20191108-sgd-e30 --allow-folder

**Comment by rachmadaniHaryono** [comment]
what i notice from `pip show pathlib` that it use external pathlib library

see the note on documentation

`This module has been included in the Python 3.4 standard library after PEP 428 acceptance. You only need to install it for Python 3.3 or older.`

**Comment by kld123509945** [comment]
> Try below command instead of `!deepdanbooru`
> 
> ```
> !python -m deepdanbooru
> ```

> 
The codes stops and reports:
> /root
> Name: pathlib
> Version: 1.0.1
> Summary: Object-oriented filesystem paths
> Home-page: https://pathlib.readthedocs.org/
> Author: Antoine Pitrou
> Author-email: solipsis@pitrou.net
> License: MIT License
> Location: /usr/local/lib/python3.6/dist-packages
> Requires: 
> Required-by: 
> Name: matplotlib
> Version: 3.1.2
> Summary: Python plotting package
> Home-page: https://matplotlib.org
> Author: John D. Hunter, Michael Droettboom
> Author-email: matplotlib-users@python.org
> License: PSF
> Location: /usr/local/lib/python3.6/dist-packages
> Requires: pyparsing, kiwisolver, cycler, numpy, python-dateutil
> Required-by: yellowbrick, stable-baselines, seaborn, scikit-image, plotnine, pandas-profiling, mlxtend, mizani, missingno, matplotlib-venn, magenta, keras-vis, imgaug, fbprophet, fastai, descartes, daft
> Usage: __main__.py evaluate [OPTIONS]
>                             [TARGET_PATHS]...
> Try "__main__.py evaluate --help" for help.
> 
> Error: Invalid value for "--project-path": Directory "deepdanbooru-v1-20191108-sgd-e30" does not exist.

**Comment by KichangKim** [comment]
It seems that colab's tensorflow is old and you should upgrade mode install it.

Here is complete sample notebook for executing DeenDanbooru on colab.
https://colab.research.google.com/drive/1BOSYlrWzBHI60NCZF18PIdmwVgsy2tCT

**Comment by kld123509945** [comment]
> It seems that colab's tensorflow is old and you should upgrade mode install it.
> 
> Here is complete sample notebook for executing DeenDanbooru on colab.
> https://colab.research.google.com/drive/1BOSYlrWzBHI60NCZF18PIdmwVgsy2tCT

OMG, thanks sooooooooo much for your patience and help! I‘ll read your share and learn the lesson from my mistakes.

**Comment by kld123509945** [comment]
Solved! It successfully runs. Thanks so much for your help!@KichangKim @rachmadaniHaryono
