### ISSUE TITLE
Dataset size

### ISSUE THREAD

**Issue by 1461748123** [KichangKim/DeepDanbooru#20]
How big is the dataset used to train the model on [DeepDanbooru Web](http://kanotype.iptime.org:8003/deepdanbooru/)?
I did a quick google search on premade Danbooru datasets and they all seemed to be exceptionally large (~3m images, ~2tb in size).

**Comment by KichangKim** [comment]
I filtered input images with tag count >= 20, so it may be 1.5~2M images, 1.5TB size.

**Comment by 1461748123** [comment]
Thank you! I honestly didn't expect the training data to be this huge :)

**Comment by OysterQAQ** [comment]
> I filtered input images with tag count >= 20, so it may be 1.5~2M images, 1.5TB size.

How long did you spend on training model?

**Comment by KichangKim** [comment]
> How long did you spend on training model?
With Ryzen 1800x + NVIDIA Geforce 2080ti, it takes about 1 month.
