### ISSUE TITLE
Cannot decode gif

### ISSUE THREAD

**Issue by Cyl18** [KichangKim/DeepDanbooru#22]
tensorflow.python.framework.errors_impl.InvalidArgumentError: Got 55 frames, but animated gifs can only be decoded by tf.io.decode_gif or tf.io.decode_image [Op:DecodePng]

**Comment by KichangKim** [comment]
Due to TensorFlow's design issue (https://github.com/tensorflow/tensorflow/issues/28247), DeepDanbooru don't use decode_image() in dataset generator. So you need to extract/convert your GIF to supported format (png or jpeg).
