### ISSUE TITLE
Can this model be used to extract features of anime pictures？

### ISSUE THREAD

**Issue by OysterQAQ** [KichangKim/DeepDanbooru#23]
first, thx for your awesome project.
Can this model be used to extract features of anime pictures？
If it can, I would like to use it to extract image features and build reverse image search system.

**Comment by KichangKim** [comment]
DeepDanbooru model returns 8k of (0.0~1.0) scores, so you can use this vector as feature vector. But it may be noisy and has too high dimension, so you may need something post-processing like PCA.

**Comment by OysterQAQ** [comment]
Yes, I noticed that it seems to output features vector of 7722 dimensions.
Will there be any problems if i use keras vgg16(imagenet) model(Exclude fc layer) to extract the features of anime pictures?
It will output 512 dimensions feature but it seems that the imagenet dataset only contains real photos

**Comment by KichangKim** [comment]
It doesn't matter what model you use, but I recommend to try DeepDanbooru model (resnet based) first because it is already trained and released so you can freely use it. Also DeepDanbooru is trained by using anime-pictures, unlike popular real-photo based models.

**Comment by OysterQAQ** [comment]
Thanks for your answer.
I prefer to use the DeepDanbooru model, but I understand that dimensionality reduction methods such as pca need to load the entire matrix, it is expensive.
Is there some better dimensionality reduction method?
The pre-trained VGG16 model still needs dimensionality reduction, because it is expensive to calculate the similarity of 512-dimensional vectors in tens of millions of pictures.

**Comment by KichangKim** [comment]
Autoencoder may be the answer I think.
https://www.tensorflow.org/tutorials/generative/autoencoder#first_example_basic_autoencoder

**Comment by OysterQAQ** [comment]
Thank you for your help. I will research it, Forgive me I am not good at deep learning
