### ISSUE TITLE
Question: creating and training my own tags

### ISSUE THREAD

**Issue by fakkunamae** [KichangKim/DeepDanbooru#24]
Can this project be generalized? I'd like to be able to use it on things like food pictures, text scraping into a tag to make it searchable on threadcaps, etc.  I dont really know anything about how to build and modify the script. Figured i'd ask.

**Comment by KichangKim** [comment]
It is possible to train with your own tag. But you need to prepare dataset yourself.

https://github.com/KichangKim/DeepDanbooru/blob/master/README.md

See Dataset Structure section and Project Structure section. You should make your own SQLite database and tags.txt by using your tags.
