### ISSUE TITLE
Load weights in Pytorch

### ISSUE THREAD

**Issue by talent-less** [KichangKim/DeepDanbooru#35]
Is it possible to convert the weights for Pytorch?

**Comment by KichangKim** [comment]
You can convert DeepDanbooru model to ONNX format by using 3rdparty library and also import ONNX to pytorch too. But I can't sure because I have never used such libraries.

https://github.com/onnx/tensorflow-onnx
https://github.com/pytorch/pytorch/issues/21683

**Comment by talent-less** [comment]
For some reason I couldn't install tf. Could you release the model in ONNX format? Thanks!!

**Comment by KichangKim** [comment]
Unfortunately I have no time for DeepDanbooru now.  I think these sites will help you:

https://github.com/ysh329/deep-learning-model-convertor
https://github.com/halcy/DeepDanbooruActivationMaps
