### ISSUE TITLE
can I have your testing website module Programe? 

### ISSUE THREAD

**Issue by lofangmeng** [KichangKim/DeepDanbooru#37]
It is because My Picture 's tag output data was totally different compare with your website even the image is a boy, it's tag come out show that the boy and girl 's  tag are both equal to 0.5+,it is weird

**Comment by lofangmeng** [comment]
![unknown(1)](https://user-images.githubusercontent.com/75239990/126600108-adea5046-181b-4e32-8615-80baf9006511.png)
![unknown](https://user-images.githubusercontent.com/75239990/126600132-b5c72b31-3dd7-4463-b8d6-41d8cec86a9b.png)
these was their different, but same picture with different data output, can I know what is the problem, why my output data is incorrect

**Comment by KichangKim** [comment]
Web demo and DD CLI uses slightly different image-preprocessing code.

See https://github.com/KichangKim/DeepDanbooru/issues/27#issuecomment-724696725

**Comment by lofangmeng** [comment]
ok thank you
