### ISSUE TITLE
show all tags?

### ISSUE THREAD

**Issue by lofangmeng** [KichangKim/DeepDanbooru#38]
how can i show out all the tags come out,cause it auto replace the lower result tags like this,
![image](https://user-images.githubusercontent.com/75239990/128817179-b42d2246-f1b4-46ee-8549-10bdc172aade.png)
where can change the condition for the tags

**Comment by KichangKim** [comment]
You can use `--threshold` option.  If you want all of tags, add `--threshold 0` to your command.

**Comment by lofangmeng** [comment]
just type deepdanbooru--threshold?

**Comment by KichangKim** [comment]
Add `--threshold 0` to your evaluation command.

**Comment by lofangmeng** [comment]
thanks ,
if i want to choose the tags only with looking at viewer or something else,just choose the tags that i need,
how can i change the code or what command can i use
is to delete the other tags is the tag_txt?

**Comment by KichangKim** [comment]
> thanks ,
> if i want to choose the tags only with looking at viewer or something else,just choose the tags that i need,
> how can i change the code or what command can i use
> is to delete the other tags is the tag_txt?

No. You should filter the results yourself. Commandline interface is just a sample. If you want more sophisticated evaluation, you should manually evaluate. I think you can start from evaluate_project.py
