### ISSUE TITLE
run the py in spyder

### ISSUE THREAD

**Issue by lofangmeng** [KichangKim/DeepDanbooru#39]
can i know that if i run this programe in spyder ,which py file is given us to run with come out those tag result

**Comment by KichangKim** [comment]
I don't know about spyder. But the entry file of DeepDanbooru is `__main__.py` 
https://github.com/KichangKim/DeepDanbooru/blob/ea22b374d1bf00b61c6c1438b58ff8da99569e54/deepdanbooru/__main__.py

**Comment by lofangmeng** [comment]
![image](https://user-images.githubusercontent.com/75239990/129129821-96ea292a-cdb2-4794-9c05-1a898feaa71b.png)
how can i run this py ,it is error?
please help me

**Comment by KichangKim** [comment]
If you want evaluate in your python code, see 
https://github.com/KichangKim/DeepDanbooru/blob/ea22b374d1bf00b61c6c1438b58ff8da99569e54/deepdanbooru/commands/evaluate_project.py

**Comment by lofangmeng** [comment]
THANKS I WILL TRY IT

**Comment by lofangmeng** [comment]
can i ask that what is the thresold,is this any files
![image](https://user-images.githubusercontent.com/75239990/129132205-96a35bd7-0336-437f-8d92-081de7faec0c.png)

**Comment by KichangKim** [comment]
It is score threshold. DD console application shows tags that its score is higher than threshold. If you want to get all tags with score, set 0.

**Comment by lofangmeng** [comment]
![image](https://user-images.githubusercontent.com/75239990/129132716-06bb53b0-9014-470c-8b68-2234dfbd22fe.png)
here is my path directory
after run the py,yt goes wrong why
![image](https://user-images.githubusercontent.com/75239990/129132693-815748f0-cc79-47c4-b792-ed23f931743f.png)

**Comment by lofangmeng** [comment]
> It is score threshold. DD console application shows tags that its score is higher than threshold. If you want to get all tags with score, set 0.

thank you

**Comment by lofangmeng** [comment]
> ![image](https://user-images.githubusercontent.com/75239990/129132716-06bb53b0-9014-470c-8b68-2234dfbd22fe.png)
> here is my path directory
> after run the py,yt goes wrong why
> ![image](https://user-images.githubusercontent.com/75239990/129132693-815748f0-cc79-47c4-b792-ed23f931743f.png)

i stuck in here i dont know what is the problem please help me thank you

**Comment by KichangKim** [comment]
Did you download pre-trained model and extract to project folder? If not, you should make project data and train model yourself.

**Comment by lofangmeng** [comment]
![image](https://user-images.githubusercontent.com/75239990/129144025-ad9675a4-9fe9-4774-b3d6-66d3b7cbdede.png)
how can i solve this problem haha i always stuck

**Comment by KichangKim** [comment]
Sorry, evaluate_project.py is old code.

See https://github.com/KichangKim/DeepDanbooru/blob/master/deepdanbooru/commands/evaluate.py instead.

**Comment by lofangmeng** [comment]
ok

**Comment by KichangKim** [comment]
allow_gpu means that allow TensorFlow uses GPU for its training/evaluating. If you have CUDA compatible GPU, set it to True.
compile_model is flag for https://www.tensorflow.org/api_docs/python/tf/keras/Model#compile

Also this method is simple python method, you can freely call this method from your python code. 
I highly recommend that read https://www.tensorflow.org/tutorials first before using DeepDanbooru with your custom code.

**Comment by lofangmeng** [comment]
thanks
![image](https://user-images.githubusercontent.com/75239990/129368398-425b5b47-42d8-453a-836f-8b91d584f887.png)
i have a new problem now it seems ready to work but still stuck at here
