### ISSUE TITLE
 'utf-8' codec can't decode byte 0xa8 in position 47: invalid start byte

### ISSUE THREAD

**Issue by lofangmeng** [KichangKim/DeepDanbooru#40]
evaluate.py
![image](https://user-images.githubusercontent.com/75239990/129432445-0d80a80d-eddc-421f-a02a-2d5a7e422383.png)

how to solve it,thanks

**Comment by KichangKim** [comment]
I can't reproduce it. Did you test DeepDanbooru CLI first?
`> deepdanbooru evaluate [image_file_path or folder]... --project-path [your_project_folder] --allow-folder`
