### ISSUE TITLE
Idiot's guide?

### ISSUE THREAD

**Issue by Churchexe** [KichangKim/DeepDanbooru#50]
I'm going to be honest and say that while I have some programming experience it's not a lot and I haven't ever programmed anything like this, not just in the AI aspect but the parsing either so these may be really stupid questions but I can't find clarification elsewhere. The instructions on the main page indicate that you have to train the network after you download it but is there anyway to just download it pretrained? Using the test website it works more than well enough for my purposes and from what I understand to train it you have to feed it tons of images from danbooru which would take download time, storage space, processor time, etc. Maybe I'm wrong and completely misunderstanding something. I know I'm misunderstanding it to some extent since it sounds like some parts contradict eachother to me but I don't know the extent to which I am. Is there a simpler guide for a stock installation or am I just missing some really simple terminology or understandings that make it click?

**Comment by KichangKim** [comment]
You can safely skip training step by using pre-trained model. You can download it from https://github.com/KichangKim/DeepDanbooru/releases/tag/v3-20200915-sgd-e30
