### ISSUE TITLE
Strange things about tensorflow-io

### ISSUE THREAD

**Issue by canoziia** [KichangKim/DeepDanbooru#58]
When I try to evaluate this image, it raised an error: 
``` shell
NotImplementedError: unable to open file: .so, from paths: ['/root/env/test/lib/python3.8/site-packages/tensorflow_io/python/ops/libtensorflow_io.so'] caused by: ['/root/env/test/lib/python3.8/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: undefined symbol: _ZN10tensorflow4data11DatasetBase8FinalizeEPNS_15OpKernelContextESt8functionIFNS_8StatusOrISt10unique_ptrIS1_NS_4core15RefCountDeleterEEEEvEE']
```
python: 3.8.10; tensorflow: 2.8.0; tensorflow-io: 0.25.0

![sdjsb20200629_151228 274](https://user-images.githubusercontent.com/54797411/167668558-b4466157-3ff1-4064-ab56-007837f3c4b5.png)

**Comment by KichangKim** [comment]
That image is actually bitmap file (even its extension is png). DeepDanbooru does not support bitmap format. Try to encode it as png or jpeg.
