### ISSUE TITLE
The BCE loss is small at the beginning of train 

### ISSUE THREAD

**Issue by gqy1025** [KichangKim/DeepDanbooru#59]
Hi, 

i tried to rerun your code step by step, and i randomly picked 10,000 pictures as my dataset from Danbooru.
when i started training, i found the loss is very small (around 0.02)  even at the very beginning.

Is this normal?

**Comment by KichangKim** [comment]
Loss may be varying by your training parameter, but 0.02 seems to be normal. DeepDanbooru web's final loss is about 0.006.
