### ISSUE TITLE
Integration of Activation maps into DD

### ISSUE THREAD

**Issue by DonaldTsang** [KichangKim/DeepDanbooru#6]
The repo in https://github.com/halcy/DeepDanbooruActivationMaps seems very slim, is it posssible to add the notebook into the mainline library for completeness sake, or better yet, improve on the library to allow for custom non-graphical outputs likes arrays and such?

**Comment by KichangKim** [comment]
It already contains command "grad-cam". It estimates all tags in input image and generate gradient map images for each tags. (But lack of post-processing so output image looks not clear)

**Comment by DonaldTsang** [comment]
Okay, what is the array dimensions of this grad-cam feature? If it is the same as the image itself then I will close this issue, since I expect this to be a weak version of image/semantic segmentation.

**Comment by KichangKim** [comment]
Its dimensions is same to the input of network, 299x299. So if you want to get the value of original image, you need to transform gradient map image to original resolution.

**Comment by DonaldTsang** [comment]
The major issue is granularity or resolution, because I do have expectations of boundaries being high def.
