### ISSUE TITLE
File Extention Clarification in Dataset Structure

### ISSUE THREAD

**Issue by Ben-Brady** [KichangKim/DeepDanbooru#64]
In the section describing the SQLite database file structure, it's not clear whether or not the `.` should be included in the file extention, it would be nice if this was clarified.

**Comment by KichangKim** [comment]
It is documented like this:

```
The filename of image must be [md5].[file_ext]
```

Is it not sufficient?

**Comment by Ben-Brady** [comment]
Yeah that is sufficient. Sorry, I should have read more clearly.
