### ISSUE TITLE
Command Not Found: deepdanbooru

### ISSUE THREAD

**Issue by crodis-strife** [KichangKim/DeepDanbooru#73]
After executing "pip install -r requirements.txt", I ran the command "deepdanbooru create-project [your_project_folder]". However, it shows the message: Command Not Found. How can I slove this problem? Thank you!

**Comment by KichangKim** [comment]
Did you run deepdanbooru installation command?
Try this
`pip install .[tensorflow]`
on your deepdanbooru folder.

**Comment by crodis-strife** [comment]
It works well after executing "pip install .[tensorflow]". Thank you!

**Comment by crodis-strife** [comment]
It only returns the evaluation results in the command window. Which files can I modify to print the evaluation results to a text file? Thank you!
 
![新點陣圖影像](https://user-images.githubusercontent.com/63531999/201527906-0ac49413-3c25-4b93-9e46-c7a2b04fead6.jpg)

**Comment by crodis-strife** [comment]
Sorry! I got it. Just using: deepdanbooru evaluate ./input --project-path project --allow-folder --save-txt
