### ISSUE TITLE
How to use DeepDanbooru for image captioning?

### ISSUE THREAD

**Issue by alienhd** [KichangKim/DeepDanbooru#75]
Hi,
how could I use DeepDanbooru for image captioning to .txt files?

**Comment by KichangKim** [comment]
DeepDanbooru is tagging application, not captioning.

**Comment by JayarCurio** [comment]
I use the train tab extension on auto1111. Check the box "Append" under "Existing Caption txt Action" and it will add the Deepbooru tags to the existing txt, so you can use together with BLIP txt caption files.
