### ISSUE TITLE
is there any GPU acceleration?

### ISSUE THREAD

**Issue by delislej** [KichangKim/DeepDanbooru#91]
hi there, i have successfully started training, but it says it will take over a month with a dataset of 280k images.

i have a 3090 with 24gb of vram, you mentioned that you trained it on a 3070, so i'm wondering if it is just the size of my data set or if i have improperly configured something. thanks!

**Comment by delislej** [comment]
please close this issue, it was an installation issue on my end.

**Comment by GenocidalStudios** [comment]
> please close this issue, it was an installation issue on my end.

What have you done to fix it?
