### ISSUE TITLE
Does "deepdanbooru-v3-20211112-sgd-e28" contain nsfw tags?

### ISSUE THREAD

**Issue by HuyNguyen1590** [KichangKim/DeepDanbooru#97]
I love this project but i don't know if this trained model contain nsfw tags.

**Comment by KichangKim** [comment]
You can use system tags like these
```
rating:safe
rating:questionable
rating:explicit
```

**Comment by HuyNguyen1590** [comment]
I mean my image may contain some nsfw tags. How can i hide those tags?

**Comment by KichangKim** [comment]
In project folder, it contains `tags.txt` file. So you can replace tags to like "REMOVED_TAG", and you can ignore `REMOVED_TAG` tag in your application.

(You should not remove tag from tags.txt. Its line number has important meaning.)

**Comment by HuyNguyen1590** [comment]
This solution sound great! Thanks for your help.
